### ISSUE TITLE
Issues with barcodeScan()

### ISSUE THREAD

**Issue by Octocat159** [DirkJanJansen/Sales-Cashregister#1] opened 2023-03-01 04:49 UTC
In Linux I'm trying to get the script to work but I'm having a problem with ```barcodeScan()``` I get the following error message
```
Traceback (most recent call last):
  File "sales.py", line 5856, in <module>
    barcodeScan()
  File "sales.py", line 5445, in barcodeScan
    calculationStock()
```

```
sqlalchemy.exc.ArgumentError: Column expression, FROM clause, or other columns clause element expected, got [Table('params', MetaData(), Column('paramID', Integer(), table=<params>, primary_key=True, nullable=False), Column('item', String(), table=<params>), Column('value', Float(), table=<params>), schema=None)]. Did you mean to say select(Table('params', MetaData(), Column('paramID', Integer(), table=<params>, primary_key=True, nullable=False), Column('item', String(), table=<params>), Column('value', Float(), table=<params>), schema=None))?
```

but if I remove the ```barcodeScan()```  from ```if __name__ == '__main__'``` and run the script it literally does nothing, is there a way to fix the problem or remove the use of ```barcodeScan()```?

**Comment by DirkJanJansen** [comment] 2023-03-14 07:57
After further investigation the problem is even odd year param is out of sync, due to more then a year not used the program


I will repair it!

17-3-2023 sales.py corrected for odd/even mismatch by program longer then a year not used (from scratch on database)
I assume that the problem is solved.
If there are still any problems let me know, otherwise i will close the issue over 14 days from now

**Comment by DirkJanJansen** [comment] 2023-03-27 10:19
Before running the first time the main program, start from folder Pandora reset_odd_even.py to set the right year to calculate stock. (In Linux cd Pandora, python3 reset_odd_even.py )

**Closed as completed by DirkJanJansen** 2023-03-27 10:19 UTC
